trigger:
- develop

pool:
  vmImage: 'windows-latest'

steps:

- powershell: |
    Write-Host "Downloading JMeter..."

    Invoke-WebRequest `
      -Uri "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip" `
      -OutFile "$(Build.SourcesDirectory)\jmeter.zip"

    Expand-Archive `
      "$(Build.SourcesDirectory)\jmeter.zip" `
      -DestinationPath "$(Build.SourcesDirectory)"

    Write-Host "JMeter installed successfully."
  displayName: 'Install JMeter'


- powershell: |
    & "$(Build.SourcesDirectory)\apache-jmeter-5.6.3\bin\jmeter.bat" -v
  displayName: 'Verify JMeter'


- powershell: |
    & "$(Build.SourcesDirectory)\apache-jmeter-5.6.3\bin\jmeter.bat" `
      -n `
      -t "$(Build.SourcesDirectory)\Horus.Planning.Admin\jmeter\HorusPlanningTest.jmx" `
      -l "$(Build.SourcesDirectory)\jmeter-results.jtl" `
      -e `
      -o "$(Build.SourcesDirectory)\jmeter-report"
  displayName: 'Run JMeter Test'


- task: PublishPipelineArtifact@1
  displayName: 'Publish JMeter Report'
  inputs:
    targetPath: '$(Build.SourcesDirectory)\jmeter-report'
    artifact: 'JMeter-Report'
